<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="13.1.1"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AspireUseCliBundle>true</AspireUseCliBundle>
        <UserSecretsId>0c853890-7b32-45cc-9bcd-cde11bcdc3d7</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AlumniBackendServices\AlumniBackendServices.csproj" />
    </ItemGroup>

</Project>
