global using Microsoft.AspNetCore.Mvc;
global using OneOf;
global using Core;
global using Infrastructure;
global using Alumni.Student;
global using Alumni.Faculty;
global using Alumni.Student.Company;
global using Alumni.Student.Exam;
global using Alumni.Student.FurtherStudy;
