<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Alumni.Auth\Alumni.Auth.csproj" />
    <ProjectReference Include="..\Alumni.Faculty\Alumni.Faculty.csproj" />
    <ProjectReference Include="..\Alumni.Student\Alumni.Student.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
</Project>
